version: "3"
services:
  app:
    container_name: ruby-sandbox
    platform: linux/amd64
    build:
      context: .
    volumes:
      - type: bind
        source: ./
        target: /app
    tty: true
