version: "3"
services:
  api:
    container_name: ruby-sandbox
    platform: linux/amd64
    build:
      context: .
    volumes:
      - type: bind
        source: ./
        target: /api
    ports:
      - "3000:3000"
