# Global variables
$DEBUG_RDOC: nil

# Classes
class Object
  private
  def fizz: (Integer n) -> String?
  def buzz: (Integer n) -> String?
  def fizz_buzz: (Integer n) -> (Integer | String)
end

class FizzBuzzTest
  def test_fizz: -> untyped
  def test_buzz: -> untyped
  def test_fizz_buzz: -> untyped
  def assert_equal: (untyped, untyped) -> void
  def assert_nil: (untyped) -> void
end
